require("config.lazy")
require("config.nvim_config")
require("config.key_mappings")
require("config.auto_cmd")
require("everforest").load()

-- Plugins --
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.telescope")
require("plugins.conform")
require("plugins.autopairs")
require("plugins.hop")
require("plugins.bufferline")
require("plugins.dashboard")
-- require("plugins.mini_pairs")

--LSP-- move to cmp.setup()
-- vim.lsp.enable('pyright')
-- vim.lsp.enable('bash-language-server')
-- vim.lsp.enable('lua-language-server')
-- vim.lsp.enable('css-lsp')
-- vim.lsp.enable('rust-analyzer')
-- vim.lsp.enable('html-lsp')
-- vim.lsp.enable('clangd')
-- vim.lsp.enable('typescript-language-server')
