unbind -a -T root

set -g pane-border-lines double

# Set base index for windows and panes to 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi # vi-mode in copy-mode

set -g mouse on

set -s escape-time 0 # wait time after esc pressed

set -g history-limit 2000



bind -n M-r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"
bind -n M-n new-window


bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9


bind -n M-v split-window -h
bind -n M-V split-window -v


bind -n M-H resize-pane -L 5
bind -n M-L resize-pane -R 5
bind -n M-K resize-pane -U 3
bind -n M-J resize-pane -D 3


bind -n M-x kill-pane
bind -n M-q kill-window
bind -n M-d detach
bind -n M-Q confirm-before -p "Kill entire session? (y/n)" kill-session

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
bind -n M-/ copy-mode \; command-prompt -p "(search down)" "send -X search-forward '%%%'"
bind -n M-? copy-mode \; command-prompt -p "(search up)"   "send -X search-backward '%%%'"


bind -n M-/ copy-mode \; command-prompt -p "(search down)" "send -X search-forward '%%%'"
bind -n M-? copy-mode \; command-prompt -p "(search up)"   "send -X search-backward '%%%'"



set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'TanglingTreats/tmux-everforest'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
run '~/.config/tmux/plugins/tpm/tpm'

