preload = /home/alexey/wallpapers/img2.akspic.ru-magistral-gorizont-nebo-infrastruktura-velosiped-6016x4016.jpg
wallpaper = DP-2, contane:/home/alexey/wallpapers/img2.akspic.ru-magistral-gorizont-nebo-infrastruktura-velosiped-6016x4016.jpg
