
monitor=HDMI-A-1,disable
monitor=DP-1,2560x1440@144,0x0,1
#monitor=DP-3,1920x1080@60,-1080x-240,1,transform,1
monitor=DP-2,disable
exec-once = regreet; hyprctl dispatch exit
#exec-once = focuswindow, pid: $(pidof regreet)
windowrulev2 = stayfocused, title:(.*)(regreet)

input 
    {
        
    numlock_by_default = true

    }

